apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/tmprvm/argo-test-repo.git
    targetRevision: master
    
    # Удалённый Helm chart
    chart: nginx
    repoURL: https://charts.bitnami.com/bitnami  # Chart источник
    targetRevision: 22.4.2
    
    # Helm values из ТОГО ЖЕ репозитория
    helm:
      parameters:
        - name: service.type
          value: NodePort
  
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  
  syncPolicy:
    automated:
      selfHeal: true
      prune: true