apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/tmprvm/argo-test-repo.git
    targetRevision: HEAD
    
    # Удалённый Helm chart
    chart: nginx
    repoURL: https://charts.bitnami.com/bitnami  # Chart источник
    
    # Helm values из ТОГО ЖЕ репозитория
    helm:
      valueFiles:
        - values/nginx/values.yaml  # Относительный путь в репозитории
      
      # Дополнительные параметры
      parameters:
        - name: service.type
          value: NodePort
  
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  
  syncPolicy:
    automated:
      selfHeal: true
      prune: true